"""Stage 6: package_status.csv (one row per park page) + DATASET_CONCERNS.md (generated from the data)."""
import glob
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
CAT = HERE / "catalog"
OUT = Path("datasets/NPS_VMI")
RAW = Path("datasets/raw/nps_vmi")
parks = pd.read_csv(CAT / "parks.csv")
prods = pd.read_csv(CAT / "products.csv")
alog = pd.read_csv(CAT / "access_log.csv")
dl = pd.read_csv(CAT / "download_log.csv")
notes = pd.read_csv(CAT / "core_build_notes.csv")
E = pd.read_parquet(OUT / "vmi_core_events.parquet")
S = pd.read_parquet(OUT / "vmi_core_species.parquet")
E4 = pd.read_parquet(OUT / "vmi_plot_events.parquet")

dp = prods[prods.type == "Data Package"][["park_name", "product_id", "units", "issued"]].rename(columns={"product_id": "data_package_id"})
dp["package"] = dp.units.str.split(";").str[0] + "_" + dp.data_package_id.astype(str)
def md_table(df):
    df = df.reset_index()
    rows = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    rows += ["| " + " | ".join(str(v).replace("|", "/") for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join(rows)


status = parks.merge(dp, on="park_name", how="left")
status["n_products"] = status.park_name.map(prods.groupby("park_name").size()).fillna(0).astype(int)
status["product_types"] = status.park_name.map(prods.groupby("park_name").type.agg(lambda s: ", ".join(sorted(set(s))))).fillna("")
fam = E.drop_duplicates("package").set_index("package").schema_family
ev = E.groupby("package").agg(plot_events=("event_key", "size"), aa_points=("plot_type", lambda s: (s == "AA").sum()),
                              with_lonlat=("lon_wgs84", "count"), first_year=("year", "min"), last_year=("year", "max"))
sp = S.groupby("package").agg(species_records=("cover_pct", "size"), with_cover=("cover_pct", "count"))
status = status.merge(ev, left_on="package", right_index=True, how="left").merge(sp, left_on="package", right_index=True, how="left")
status["schema_family"] = status.package.map(fam)
dfail = dl[~dl.result.isin(["ok", "cached"])].groupby("dir").size()


def classify(r):
    if not r.page_ok:
        return "park page not available (404)"
    if pd.isna(r.project_ids) or r.project_ids == "":
        return "park page has no IRMA project link"
    if pd.isna(r.data_package_id):
        return "no open-format data package (only: " + (r.product_types or "nothing") + ")" if r.n_products else "IRMA project returned no products"
    if pd.notna(r.schema_family):
        return "harmonized"
    d = r.package.split("_")[0]
    return "downloaded, NOT yet harmonized (custom schema)"


status["status"] = status.apply(classify, axis=1)
status["download_failures"] = status.package.map(dfail).fillna(0).astype(int)
status.to_csv(CAT / "package_status.csv", index=False)
print(status.status.value_counts())

# ------------------------------------------------------------------ DATASET_CONCERNS.md
md = ["# NPS Vegetation Mapping Inventory (VMI) plot data: dataset questions and concerns", "",
      "Generated by `06_status_and_concerns.py` from the downloaded packages. General cautions first, then one block per park package.", "",
      "## Cross-cutting concerns", "",
      "- **Purpose.** Plots were collected to *classify vegetation (USNVC associations)* and to *assess map accuracy*, not for monitoring. Plots are subjectively placed in homogeneous stands, so they are not a probability sample of the park.",
      "- **Two kinds of record.** `plot_type = plot` are classification plots (full species lists, quantitative cover). `plot_type = AA` are accuracy-assessment points, often visited quickly with a short or presence-only species list; do not mix them without thought.",
      "- **Cover is not on one scale.** Species cover is reported either as a percent (`reported`) or as a park-specific cover class converted to a midpoint (`class_midpoint*`). Class schemes differ between parks (e.g. 6-, 10- and 14-class versions). Check `cover_pct_source`. `class_midpoint_assumed_ncpn_scheme` means the park's lookup table had no percentages and I applied the standard NCPN scheme. Verify before relying on it.",
      "- **Cover is by stratum and can exceed 100%** when summed across strata or species (overlapping canopy). Stratum codes (T1-T3, S1-S3, H, N, V, E, A...) have park-specific height definitions (`tProjectMetadata`); strata are not comparable across parks without that table.",
      "- **Plot size and shape differ** (circular, square, rectangular, 'quickplot', observation point). Cover and richness are not comparable across plot sizes. Plot dimensions are in the raw tables but are NOT harmonized here.",
      "- **Community labels (NVC) are uneven.** `nvc_code_source` says where a label came from: `final_classification` (park's final association code/name), `aa_field_call` (accuracy-assessment mapper's primary call, lower confidence) or `name_match_to_catalog` (the source gave only a name; matched to the current NVC catalog). Codes that are park-local (NPSxxxx, NHNM...), provisional (CEPP/CEPS) or retired CEGL codes do not resolve (`nvc_resolved = False`) and give no `community_name`. Labels reflect the NVC version at survey time.",
      "- **Dates.** Surveys range from the mid-1990s to the 2010s. Many datasets are 10-25 years old relative to current imagery, and the source timestamps carry a spurious UTC time-of-day. Check `year` against your imagery dates.",
      "- **Coordinates are repaired, not original.** Raw X/Y, zone and datum are kept (`x_raw`, `y_raw`, `utm_zone_raw`, `datum_raw`). Repairs applied and flagged in `qa_flags`: `utm_zone_inferred` / `utm_zone_corrected` (zone chosen so the point falls in the park's bounding box), `utm_xy_swapped`, `latlon_swapped_lon_sign_assumed`, `lon_sign_assumed`. Positional accuracy (GPS error, WAAS, differential correction) varies from ~1 m to tens of meters and pre-2000 points may be map- or SA-era GPS. The `GPS_Error` field is in the raw tables.",
      "- **Datum.** Mostly NAD83 (WGS84 where stated); I treat anything not containing 'WGS' as NAD83. The difference is ~1 m in the US and negligible here.",
      "- **Sensitive-species fuzzing.** Some PLOTS v4 packages carry `Public_X/Public_Y` and `Sensitive_Data` in `tPlots` (see raw tables); I use the field coordinates `Field_X/Field_Y`, which may be the precise location. Treat as sensitive if you publish.",
      "- **Taxonomy.** Species names come from different nomenclatural sources (USDA PLANTS circa the survey year, ITIS TSN, park checklists). No synonymy resolution has been done. Names are not matched across parks.",
      "- **Not all packages are plot data.** 'Data Package' = an *open-format* export of the park's PLOTS database made by NPS in 2022-2025. Empty source tables stay empty. Some contain only accuracy-assessment data.",
      "- **Duplicates across packages.** Some packages bundle other parks' data (e.g. MORA contains NOCA/OLYM species rows; BEOL contains Sand Creek `SAND.*` plots; Point Reyes/Golden Gate and Lake Mead-type packages cover several units). Orphan species rows are dropped and logged in `catalog/core_build_notes.csv`.",
      "", "## Access summary", "", md_table(status.status.value_counts()), "",
      "Full table: `catalog/package_status.csv`; every HTTP access (200/404/500) is in `catalog/access_log.csv`.", ""]

meta = []
for pk in sorted(set(status.package.dropna())):
    r = status[status.package == pk].iloc[0]
    lines = [f"### {r.park_name} ({pk})", ""]
    lines.append(f"- Status: **{r.status}**. Data package: https://irma.nps.gov/DataStore/Reference/Profile/{pk.split('_')[1]}")
    if r.status == "harmonized":
        e = E[E.package == pk]
        s = S[S.package == pk]
        lines.append(f"- {len(e)} events ({(e.plot_type=='AA').sum()} AA points), {len(s)} species records; schema `{r.schema_family}`; years {e.year.min():.0f}-{e.year.max():.0f}." if e.year.notna().any() else f"- {len(e)} events, {len(s)} species records; schema `{r.schema_family}`; **no valid survey dates**.")
        lab = e.nvc_resolved.sum()
        lines.append(f"- Community labels: {lab} of {len(e)} events resolve to an NVC type ({lab/len(e):.0%}); {e.freeform_community_name.notna().sum()} have a freeform field community name; label sources: " + (", ".join(f"{k} {v}" for k, v in e.nvc_code_source.value_counts().items()) or "none") + ".")
        nll = e.lon_wgs84.isna().sum()
        if nll:
            lines.append(f"- {nll} of {len(e)} events have no usable coordinates ({nll/len(e):.0%}).")
        fl = e.qa_flags.fillna("").str.split(";").explode().value_counts()
        for k, v in fl.items():
            if k and v:
                lines.append(f"- Coordinate flag `{k}`: {v} events ({v/len(e):.0%}).")
        if len(s):
            src = s.cover_pct_source.value_counts(dropna=False)
            lines.append("- Cover provenance: " + ", ".join(f"{('none' if pd.isna(k) else k)} {v/len(s):.0%}" for k, v in src.items()))
        if e.year.isna().mean() > 0.1:
            lines.append(f"- {e.year.isna().mean():.0%} of events lack a survey date.")
        for _, n in notes[notes.package == pk].iterrows():
            lines.append(f"- Build note: {n.note}")
        md_f = glob.glob(f"{RAW}/{pk}/*tProjectMetadata.csv")
        if md_f:
            m = pd.read_csv(md_f[0], dtype=str, keep_default_na=False, na_values=["NA", ""], encoding_errors="replace")
            if len(m):
                m = m.iloc[0]
                for k in ("Sampling_Method", "Project_Comments", "Coordinate_Method", "Datum"):
                    if pd.notna(m.get(k)):
                        lines.append(f"- Project metadata `{k}`: {' '.join(str(m[k]).split())[:300]}")
    elif r.status.startswith("downloaded"):
        files = sorted(Path(f).stem for f in glob.glob(f"{RAW}/{pk}/*.csv"))
        lines.append(f"- Custom schema; {len(files)} tables, none auto-mapped. Question: which tables hold plot location, visit date and species cover? See `catalog/package_profile.csv`.")
    meta.append("\n".join(lines))
md += ["## Per-package notes", ""] + [m + "\n" for m in meta]
md += ["## Parks without a harmonizable data package", "", md_table(status[~status.status.isin(["harmonized"]) & status.package.isna()][["park_name", "status"]].set_index("park_name")), ""]
(HERE / "DATASET_CONCERNS.md").write_text("\n".join(md))
print("wrote DATASET_CONCERNS.md,", len(md), "blocks")
